# Specify a base image
FROM node:alpine

# define work directory
WORKDIR /app

# copy required files for installation of software
COPY ./package.json ./

# Install the dependencies
RUN npm install

# copy other files
COPY ./ ./

# Default command
CMD ["npm", "run", "start"]
